// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtfF94Zfw5qoONBQTEoCbpOXgmvivqUhw',
    appId: '1:250180446498:web:24dfcfc4049db613705d7b',
    messagingSenderId: '250180446498',
    projectId: 'flutter-ecommerce-6ad81',
    authDomain: 'flutter-ecommerce-6ad81.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-6ad81.appspot.com',
    measurementId: 'G-F9RVWQVLXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLP6tBX11xi0gpbSUnU1S95nlrW2i5Yeg',
    appId: '1:250180446498:android:4a0e0d859cf58c81705d7b',
    messagingSenderId: '250180446498',
    projectId: 'flutter-ecommerce-6ad81',
    storageBucket: 'flutter-ecommerce-6ad81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1TX5Ai7n67YcYp9EEiitiGc9vRAeg5Eo',
    appId: '1:250180446498:ios:e7544614a8b6fe57705d7b',
    messagingSenderId: '250180446498',
    projectId: 'flutter-ecommerce-6ad81',
    storageBucket: 'flutter-ecommerce-6ad81.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1TX5Ai7n67YcYp9EEiitiGc9vRAeg5Eo',
    appId: '1:250180446498:ios:dd702f812f1192a8705d7b',
    messagingSenderId: '250180446498',
    projectId: 'flutter-ecommerce-6ad81',
    storageBucket: 'flutter-ecommerce-6ad81.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}